### ISSUE TITLE
Module hasn't set a label for an action

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion-module-casparcg-server#30]
See https://github.com/bitfocus/companion/issues/2963 for more background or ask @Julusian 

              this seems like a module has done something wrong and hasnt set a label for an action.
Ill add a guard to avoid this error, but it would be a good idea to figure out which module is causing so that it can be corrected there

_Originally posted by @Julusian in https://github.com/bitfocus/companion/issues/2963#issuecomment-2254609552_

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-module-casparcg-server/blob/42bddbb455a04b060d6a40c41db71b5da76522a9/actions.js#L217 this one. The rest are using `name`, this one is still `label`

**Comment by peternewman** [comment]
Thanks @julusian . See #31 for a fix.
